resources:
  - namespace.yaml
  - mariadb-pvc.yaml
  - owncloud-pvc.yaml
  - mariadb-deployment.yaml
  - mariadb-service.yaml
  - owncloud-deployment.yaml
  - owncloud-service.yaml
  - redis-pvc.yaml
  - redis-deployment.yaml
  - redis-service.yaml
