apiVersion: apps/v1
kind: Deployment
metadata:
  name: owncloud
  namespace: owncloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: owncloud
  template:
    metadata:
      labels:
        app: owncloud
    spec:
      containers:
        - name: owncloud
          image: docker.io/owncloud/server:10.15
          ports:
            - containerPort: 8080
          env:
            - name: OWNCLOUD_DOMAIN
              value: 192.168.1.113
            - name: OWNCLOUD_DB_TYPE
              value: mysql
            - name: OWNCLOUD_DB_HOST
              value: mariadb
            - name: OWNCLOUD_DB_NAME
              value: owncloud
            - name: OWNCLOUD_DB_USERNAME
              value: owncloud
            - name: OWNCLOUD_DB_PASSWORD
              value: owncloudpass
            - name: OWNCLOUD_ADMIN_USERNAME
              value: admin
            - name: OWNCLOUD_ADMIN_PASSWORD
              value: adminpass
            - name: OWNCLOUD_SKIP_CHOWN
              value: "true"
            - name: OWNCLOUD_SKIP_SET_PERMISSIONS
              value: "true"
            - name: OWNCLOUD_CRON_MODE
              value: "webcron"
            - name: OWNCLOUD_CROND_ENABLED
              value: "false"
            - name: OWNCLOUD_BACKGROUND_MODE
              value: webcron
            - name: REDIS_HOST
              value: redis
            - name: REDIS_PORT
              value: "6379"
            - name: OWNCLOUD_REDIS_HOST
              value: redis
            - name: OWNCLOUD_REDIS_PORT
              value: "6379"
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
          volumeMounts:
            - name: owncloud-data
              mountPath: /mnt/data
      volumes:
        - name: owncloud-data
          persistentVolumeClaim:
            claimName: owncloud-data
