apiVersion: v1
kind: ConfigMap
metadata:
  name: runner-config-v2
  namespace: gitlab-runner-v2
data:
  config.toml: |
    [[runners]]
      executor = "kubernetes"

      [runners.kubernetes]
        namespace = "gitlab-runner-v2"
        image = "registry.access.redhat.com/ubi9/ubi:9.6"
        privileged = false
        poll_timeout = 600

        cpu_request = "300m"
        cpu_limit = "2"

        memory_request = "512Mi"
        memory_limit = "4Gi"

        helper_cpu_request = "100m"
        helper_memory_request = "128Mi"

        service_cpu_request = "100m"
        service_memory_request = "128Mi"
