---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgC2uuxCCJ6rSDjlU2HjPipfeXRyCR4rZ/ZVJq6JVPR8MYvmoP7bdMu5HMe2u4Wz/0se1UyBWXQ2hiZ/Hk72wP9BKIL6IeoxVE1g7DXe5KULlkZT4ARnaFXj7gW928rnA89mbVa22UNxG5YNNo0BnlVYVdo1bHoWU2Yajsr+W9zNmJFO9vvPnxJNrtmECxnwPNk1wK4v7PV0pgQX3MYTO+uEvHy7D6tCMEOpGd6izX8G9AkltKmGmQnDJRQ1lr4RcbkbK5ZRRylrBU/qFKM1sNj3Allcs2fZo23LGsVgq1lQfZ8g6/SqfoAJ+UbHoLwVHzwv2yFmT4rekFSeUmEPBLUSbhVSUbZNCaOsfl3/Bxh11vW0AplNWmkZKxbq/3Iw2yq9DMqJisuqYO03k+usGmSDPrJO9uqJ6B3NPVuC/x1Siw4+Kyu/7vA2DtEnfv/wncz+87bvEaao4Od4l+qR6bd8HcB8zR4r1r2+xEA3Tph/rjhnL63XAnFlQEoD4iX3TCdz1rn94vy2urBnQQDgRZXHneqtDBSryqtCY4aPbZBwheAl1oevRsg5bzWaR9uHe8rEr5uQmZmYljGWfRwlP1gsSswpP14nylf5FXDczO0CRdnktNxV3sTD2S0uvb6oyYWjERVKx6HajnuDDMRuU9fVEe/ggYvN+nbrcr2juPtsdaxTRtMXc9UBiOMsqbo5IR6i056pCraIXiThGRJYi7qfNzS2xQ==
    admin-user: AgBXuK/GMY/6Cp/1MhCM8pWglqNk3LdT2SfXaz0LZsbML+MKuNmACEjhi8u60U0jeT5n/MkVSlKDBqfrdHTGZqhZPzLnt56XYfIGljWDYfInauwkeDgyADFB5Rtei14O0ppBVIC4p2k56VmnMIRUH6f/zVy0uJNo8qXIS6Gcpm2UoV5Jx1tukg7eP8XqetXYjkZu7UjN2ACWo8+cFYUkeQqgqP3oKj/N3f7BEUgAkYN1N5BI//uMxJZTzzlRANtZFzASZnBNWUXrc+viE/4W/BrZnlU04Yo39yQUjU+40qZEitbEgzX52ReEhI6cucAwuz1KIdZm82LNj14r4h2WXfqgsorYwUavkqspTR959ie6/k2KbJqNq14d1itsLb1yeNxthkoDyJSlrHGd7Z+eEFYa8g7tpt3YZXFb2B3nIkauiIVmD7VsXHa33dRjtYiw5zouYzKXkxF6t8UxawpFZxefZmaakInJ+l66kIA/dkrYv6hsq2jwRbrqh6OfCDZcvt1c2RPjDeo6rcpZ7AulPUgpAkeBvH0raWIHHAcZjzgjFt7TFBtkySMoIR76LE/fjGwd8DAHkd74RqbyljHLmHR7wNntMjFYAjkiXsNYDwZGG1Hej1D+23ChgZJXX7cR4G55o/ze5v6kLUNldR1pk8T7CsUInA7uegwgU/Sl8XrBsSbluUROtWGY4F/VjFoYw3Cbwt4s2A==
  template:
    metadata:
      name: grafana-admin
      namespace: monitoring
