apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - node-exporter/sa-rbac.yaml
  - node-exporter/daemonset.yaml
  - node-exporter/service.yaml
  # - node-exporter/rolebinding.yaml
  - kube-state-metrics/sa-rbac.yaml
  - kube-state-metrics/deployment.yaml
  - kube-state-metrics/service.yaml
  - prometheus/deployment-service.yaml
  - prometheus/configmap.yaml
  - grafana/deployment-service.yaml
  - grafana/route.yaml
