resources:
  - argocd-install.yaml
  - argocd-route.yaml


patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: argocd-redis
    path: patch-argocd-redis-securitycontext.yaml


  - target:
      version: v1
      kind: ConfigMap
      name: argocd-cmd-params-cm
    path: patch-argocd-cmd-params-json6902.yaml