apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: observability

resources:
  - 00-namespace.yaml
  - 01-node-exporter.yaml
  - 02-kube-state-metrics.yaml
  - 03-prometheus.yaml
  - 04-grafana.yaml

configMapGenerator:
  - name: grafana-dashboard
    files:
      - grafana-dasboard/microshift-node-1860.json
      - grafana-dasboard/microshift-node-13332.json
    options:
      disableNameSuffixHash: true

