apiVersion: v1
kind: ConfigMap
metadata:
  name: runner-proxy-env
  namespace: gitlab-runner
data:
  HTTP_PROXY: "http://proxy.example.com:1234"
  HTTPS_PROXY: "http://proxy.example.com:1234"
  NO_PROXY: ".local,.svc,localhost,127.0.0.1,"
