apiVersion: v1
kind: ConfigMap
metadata:
  name: gitlab-runner-config
  namespace: gitlab
data:
  config.toml: |
    concurrent = 2
    check_interval = 10

    [[runners]]
      name = "microshift-runner"
      url = "https://gitlab.com/"
      executor = "kubernetes"

      [runners.kubernetes]
        namespace = "gitlab"
        image = "alpine:3.19"
        privileged = false
        allow_privilege_escalation = false
        cpu_limit = "500m"
        memory_limit = "512Mi"
        service_cpu_limit = "200m"
        service_memory_limit = "256Mi"

