apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - 00-namespace.yaml
  - 01-operatorgroup.yaml
  - 02-subscription.yaml
  - 03-secret-token.yaml
  - 04-configmap-runner.yaml
  - 04b-configmap-proxy.yaml
  - 05-gitlabrunner.yaml
