apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: owncloud
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/headii/k8s_deplyments.git
    targetRevision: main
    path: deployments/owncloud
  destination:
    namespace: owncloud
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true